/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.asrr.core

class Library {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
        }
    }
}
