/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.asrr.common

import org.springframework.boot.runApplication


class Library {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
        }
    }
    fun someLibraryMethod(): Boolean {
        return true
    }
}
