/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.asrr.core

import org.junit.jupiter.api.Test

class LibraryTest {

    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = Library()
    }
}
