/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.asrr.common

import org.junit.Test
import org.junit.jupiter.api.Assertions

class LibraryTest {

    @Test
    fun testSomeLibraryMethod() {
        val classUnderTest = Library()
        Assertions.assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
