name: Tag

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Gradle
        run: ./gradlew build

      # Publish the artifact to Nexus
      - name: Publish to Nexus
        run: ./gradlew publish --no-daemon
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

      # Optional: Upload coverage reports to Codecov
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ./src/backend/build/reports/jacoco

      # Set up Node.js for Semantic Release
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Set up semantic-release
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec semantic-release/git semantic-release/release-notes-generator conventional-changelog-conventionalcommits

      # Run Semantic Release to create releases based on commit messages
      - name: Release
        env:
          GIT_AUTHOR_NAME: asrr[bot]
          GIT_COMMITTER_EMAIL: dev@asrr.nl
          GIT_COMMITTER_NAME: asrr[bot]
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_TOKEN }}
        run: npx semantic-release